import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/common/Header";
import { signOut, useSession } from "next-auth/react";
import { useState, useEffect } from "react";
import useSpotify from "../hooks/useSpotify";


export default function Home() {
	const spotifyApi = useSpotify();
	const { data: session, status } = useSession();
	const [playlists, setPlaylists] = useState([]);

	console.log(session)
	useEffect(() => {
		// if (spotifyApi.getAcessToken()) {
		//   spotifyApi.getUserPlaylists().then((data) => {
		//     setPlaylists(data.body.items)
		//   })
		// }
	}, [session, spotifyApi]);

  return (
		<>
			<Head>
				<title>Groovehub</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.container}>
				<div>
					<Header />
          <button onClick={() => {
            signOut()
          }}>Logout</button>
				</div>
			</main>
		</>
	);
}
